# Generated by Django 5.2.11 on 2026-02-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_skillanalytics_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillanalytics',
            name='job_role',
        ),
        migrations.AddField(
            model_name='analysis',
            name='job_role',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
