# Generated by Django 5.2.11 on 2026-02-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_skillanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillanalytics',
            name='job_role',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
